import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Footer, NavbarTop } from "./components/Navbar";
import { Analytics } from "@vercel/analytics/next";
import { SpeedInsights } from "@vercel/speed-insights/next";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  // title: "Create Next App",
  title: "Jinny Space",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex h-full bg-zinc-50">
          <div className="flex w-full">
            <div className="fixed inset-0 flex w-full justify-center px-8">
              <div className="flex w-full max-w-7xl px-8 /*bg-amber-300">
                <div className="w-full bg-white ring-1 ring-zinc-100"></div>
              </div>
            </div>
            <div className="relative flex w-full items-center flex-col">
              {" "}
              {/* 导航栏 */}
              <NavbarTop />
              {/* 中间容器 */}
              {children}
              {/* 网络分析 */}
              <Analytics />
              {/* 速度分析 */}
              <SpeedInsights />
              {/* 底部导航栏 */}
              <Footer />
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
